# This is a basic workflow to help you get started with Actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    
    steps: 
      - name: test
        uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "prometheus --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }} # automatically provided
